# -*- coding: utf-8 -*-
"""8_loops_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTxRMv91YPk8RxeQGA1QuWJykmHl5Dph
"""

for i in range(0,10):
  if i==3:
    continue
  print(i)

for i in range(0,5):
  for j  in range(2,6):
    print(i,j)
    if j==3:
      break

for i in range(0,5):
  for j in range(1,5):
    if j==3:
      continue
    print(i,j)

for i in range(1,5):
  for j in range(1,5):
    if i==3:
      continue
    else:
      print(i,j)

row=5
for i in range(1,row+1):
  print(" "(row-i)+i"*")

for i in range(1,6):
  for j in range(1,i+1):
    print((i+j)%2,end=" ")
  print()

row=7
for i in range(1,row):
  for j in range(1,row-i):
    print(j,end=" ")
  print()

for i in range(1,6):
  for j in range(1,6):
    print((i+j)%2,end=" ")##checker board pTTERN
  print()



