# -*- coding: utf-8 -*-
"""class_2_python.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nZ104skgGuh3eCukrh-mwwsde5WULxD3
"""

a=10
b=10

a

b

a_=20

a_

import keyword
print (keyword.kwlist)

a=10+6j

a

type(a)

string='''dada
science
machine
learning'''

type(string)

String1="machine learning"
len(String1)

print(String1[0:6])

String1[4:7]

string

string4="data science"

string4.upper()

string5="machine learning"

string5.upper()

#next set

string="DATA"

string.isalpha()

string.isalnum()

string.isnumeric()

data="   "

data.isspace()

string="data science"

string.split()

string.split("a")