# -*- coding: utf-8 -*-
"""class_5_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jTLucky0oAq9oPncAF4j9_jMWVR006u9
"""

d={"key":10 , "key":20}

d

type(d)

mixed_dict = {
    "name": "Alice",
    101: [80, 85, 90],
    3.14: {"unit": "pi"},
    True: "Active"}

mixed_dict

employee = {
    "id": 1007,
    "name": "Priya Sharma",
    "department": {
        "name": "Data Science",
        "location": "Hyderabad",
        "floor": 3
    },
    "is_active": True
}

employee['department']['location']

temp={
   "lat":33.44,
   "lon":-94.04,
   "timezone":"America/Chicago",
   "timezone_offset":-18000,
   "current":{
      "dt":1684929490,
      "sunrise":1684926645,
      "sunset":1684977332,
      "temp":292.55,
      "feels_like":292.87,
      "pressure":1014,
      "humidity":89,
      "dew_point":290.69,
      "uvi":0.16,
      "clouds":53,
      "visibility":10000,
      "wind_speed":3.13,
      "wind_deg":93,
      "wind_gust":6.71,
      "weather":[
         {
            "id":803,
            "main":"Clouds",
            "description":"broken clouds",
            "icon":"04d"
         }
      ]
   } }

temp['current']['weather'][0]['main'].upper()

d = {
    "name": "Alice",
    "age": 25,
    "location": "Bangalore"
}

d

d.items()

x={11,12,1,3,1,4,1,4,1,5}

x={11,12,1,3,1,4,1,4,1,5}
x

y=frozenset([1,3,4])

y