# -*- coding: utf-8 -*-
"""class_3_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bz9Ne4dPGp4MqQYnwkky0sH9CLJ-hfxw
"""

x="data"

len(x)

x.upper()

x="data science"
x.find("s")

x="data science"
x.find("sci")

x="data science"
x.find("tes")

x="data science"
x.index("s")

x=" data "
x.strip()

x.lstrip()

x.rstrip()

x="dataD"

x.replace("D","xyz")

x="20"
x.zfill(7)

x=''' data
science '''

x="data \n science"
x.splitlines()

" ".join("data")

" ".join("hello")

" ".join("hello")

x=['data','science']
"".join(x)

x=[1,2,3,4,"data"]

#list data types

type(x)

x=[1,2,3,4.5,"data"]
type(x)

x

x[0]

x[-1][-1]

x[2:3]

x[3:2]

x

print(x[0],type(x[0]))
print(x[1],type(x[1]))
print(x[2],type(x[2]))
print(x[3],type(x[3]))
print(x[4],type(x[4]))

x[-1].upper()[0:2]

x[-3]/2

x=["data","science","machine","learning"]

x

x[-1]

x[2][-1].upper()

weekly_sales = [
    ["Chennai", [12000, 15000, 17000]],  # Mon, Tue, Wed
    ["Delhi", [10000, 11000, 10500]],
    ["Kolkata", [9000, 9500, 9800]]
]

x=[1,2,3,4]

x.append(15)

x

x.extend("data")

x

x=[1,2,3]
y=[4,5,6]
x.extend(y)

x

x=[1,2,3]
y=[4,5,6]
x.append(y)

x

x=[1,2,3,4]
x.insert(-2,"data")
print(x)

x=[1,2,3,4]

x.pop(2)

x=[1,2,3,4]
x.remove(2)
print(x)

x=[1,2,3,4]
x.count(2)

x=[1,2,3,4,2,2,3,4,2,5]
x.index(2)



