# -*- coding: utf-8 -*-
"""class_4_python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ogLTp0peaBvq6biJiQE3hbEwkk6omwNT
"""

x=[1,2,3.9,5,"data",[10,20,30]]
type(x)

len(x)

x=[1,2,3,4]
y=[4,5,6]
x.extend(y)

x

x=[1,2,3,4]
y=[4,5,6]
x.extend(y)
len(x)

x=[11,12,13,14,15]
x.sort(reverse=True)

x

x=[11,12,13,1,4,15,11,12,112,1,11]
x.count(11)

x=[1,2,3,4,5]
y=x[2:4].copy()
print(y)
y[0]=9999
print(y)
print(x)

x=[1,2,3,4,5]
y=x  ### Shallow copy
y[0]=99999
print(y)
print(x)

x=[1,2,3,4,5]
y=x
y[0]=99999
print(y)
print(x)

x={1,2,5,6,7,"data","science"}
y={1,2,5,8,9,10,"data","analytics"}
x.union(y)

x={1,2,5,6,7,"data","science"}
y={1,2,5,8,9,10,"data","analytics"}
x.intersection(y)

x={16,20}
y={3,4}
print(x.issubset(y))
print(y.issubset(x))
print(x.issuperset(y))
print(x.isdisjoint(y))

x=[1,2,3,4]

x.clear()
x

x={1,2,3,4,5}
y={4,5,6,7,8}
x.symmetric_difference(y)

x={1,2,3,4,5}
y={4,5,6,7,8}
x.symmetric_difference_update(y)
print(x)
print(y)

x={1,2,3,4,5}
y={4,5,6,7,8}
x.intersection_update(y)
print(x)
print(y)

x={1,2,3,4,5}
x.pop()
x

x

x={10,20,30}
y=x.copy()
y.add(100)
print(x)
print(y)